### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by lteu** [bendodson/MTG-VNRecognizeTextRequest#1]
Hi, I got a number of errors:

Use of undeclared type 'UIWindowSceneDelegate'
Use of undeclared type 'UIScene'

Regards,
Tony

**Comment by bendodson** [comment]
@lteu what version of Xcode are you using? This will only work with Xcode 11 and the iOS 13 SDK.

**Comment by lteu** [comment]
Thanks for the info; Indeed, I was using Version 10.3. I guess Xcode 11 should be the beta version at this moment. 

Tony
